#Updates Stuff and removes stuff

---
- name: updates Stuff
  hosts: pi
  remote_user: matthew
  become: yes

  tasks:
  - name: Updating OS
    apt:
      upgrade: yes
      update_cache: yes
  - name: ensure python is up to date
    apt: 
      name: python
      state: latest
  - name: ensure samba is up to date
    apt: 
     name: samba
     state: latest
  - name: uninstalls groovy
    apt: 
      name: groovy
      state: absent
