---
- hosts: pi
  become: yes
  remote_user: matthew
  tasks:
    - name: install dependencies
      yum:
        name: "{{ package }} "
        state: present
      vars:
        package:
        - wget
        - default-jre
        - git
      
    - name: download jenkins.repo
      get_url:
        url: https://pkg.jenkins.io/debian-stable binary/
        dest: /etc/apt/sources.list

    - name: import jenkins key
      rpm_key:
        state: present
        key: https://pkg.jenkins.io/debian-stable/jenkins.io.key

    - name: install Jenkins
      yum:
        name: jenkins
        state: present

    - name: Start Jenkins
      service:
        name: jenkins
        state: started
        enabled: yes

    - name: Wait until Jenkins is up
      shell: result_first=1; while [[ $result_first != 0 ]]; do if [[ `grep 'Jenkins is fully up and running' /var/log/jenkins/jenkins.log` ]];then result_first=0;else sleep 4;fi;done
      register: result
      until: result.rc == 0
